version: "3.5"

services:
  exporter:
    build: ..
    image: kalkspace/orno-exporter
    devices:
      - /dev/ttyUSB0
    environment:
      ORNO_SERIAL_ADDRESS: /dev/ttyUSB0
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus:v2.13.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom-data:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:6.3.6
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./datasources.yml:/etc/grafana/provisioning/datasources.yml
    environment:
      GF_SECURITY_ADMIN_PASSWORD: kalkspace
      GF_AUTH_ANONYMOUS_ENABLED: "true"

volumes:
  prom-data:
  grafana-data:
