---
name: Build binaries
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["linux", "darwin", "windows"]
      fail-fast: false
    name: Build
    steps:
      - uses: actions/checkout@master
      - name: Build binary
        uses: docker://golang:1.13-alpine
        with:
          entrypoint: /bin/sh
          args: build.sh
          env:
            CGO_ENABLED: 0
            GOOS: ${{ matrix.os }}
