---
name: Upload release binaries
on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - os: "linux"
            file: "orno-exporter_linux"
            type: "application/octet-stream"
            configfile: "/etc/orno-exporter.conf"
          - os: "darwin"
            file: "orno-exporter_macos"
            type: "application/octet-stream"
          - os: "windows"
            file: "orno-exporter_win.exe"
            type: "application/vnd.microsoft.portable-executable"
      fail-fast: false
    name: Build & Upload binaries
    steps:
      - uses: actions/checkout@master
      - name: Build binary
        uses: docker://golang:1.13-alpine
        with:
          entrypoint: /bin/sh
          args: build.sh
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.os }}
          BIN_FILE: ${{ matrix.arch.file }}
          GO_LDFLAGS: -X github.com/kalkspace/orno-exporter/main.ConfigFile=${{ matrix.arch.configfile }}
      - name: Upload binary
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ matrix.arch.file }}
          asset_name: ${{ matrix.arch.file }}
          asset_content_type: ${{ matrix.arch.type }}
